name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - "0.21"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # if you have any dependencies

      - name: Build Sphinx Documentation
        run: |
          sphinx-build . _build/html  # Adjust paths if necessary
        env:
          TZ: UTC

      # buildディレクトリのアーティファクトとして保存
      - uses: actions/upload-artifact@v4
        with:
          path: _build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      # Deploy to the github_pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html # Adjust the path to your build directory
